### ISSUE TITLE
Unset a config key

### ISSUE THREAD

**Issue by jappievw** [punkstar/mageconfigsync#5]
We are using the mageconfigsync to roll out required config changes on all environments with our CI. However, sometimes we feel the need to to revert a previously set config key to a state in which is should be unset. Is there a hidden feature in the way to mark a feature as forced unset?

**Comment by punkstar** [comment]
It's great to hear that it's being baked right in with your CI process!

There is, at present, no mechanic for unsetting a value from the Magento configuration, i.e. deleting the record from `core_config_data`, although it's something I'd like to build in. 

In terms of how to achieve that, YAML natively supports `null` as a value which would be mapped to PHP's `null` during parsing.  I propose, when a `null` value is encountered in the YAML, it be treated as a value delete request, instead of a value update request, thereby dropping the record from `core_config_data`.

**Comment by jappievw** [comment]
During the implementation I realized that Magento treats a NULL value as unset. This means that we only need to change the console display of unsetting a value. Removing a `core_config_data` entry in the database would make Magento recreate them each time again for some config sections.

**Comment by jappievw** [comment]
PR #6 fixes the issues with regards to the display of the config keys marked as "inherit from parent".
